# core/report_engine.py

import json
from datetime import datetime


class ReportEngine:

    def generate_summary(self, data):
        """Generate a clean human-readable summary report"""

        issues = data.get("issues", [])
        complexity = data.get("complexity", {})

        high = len([i for i in issues if i.get("score", 0) >= 0.85])
        medium = len([i for i in issues if 0.6 <= i.get("score", 0) < 0.85])
        low = len([i for i in issues if i.get("score", 0) < 0.6])

        return f"""
==============================
🧠 AI BUG REPORT SUMMARY
==============================

📅 Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

📊 COMPLEXITY
- Score: {complexity.get('complexity_score')}
- Risk: {complexity.get('risk')}

🐞 ISSUES BREAKDOWN
- High: {high}
- Medium: {medium}
- Low: {low}
- Total: {len(issues)}

🧾 OVERVIEW
This report was generated by AI Bug Localizer PRO system.
It analyzes syntax, runtime, and logic issues.
"""

    def generate_json_report(self, data):
        """Clean JSON export for download"""

        clean_data = {
            "timestamp": datetime.now().isoformat(),
            "code": data.get("code"),
            "issues": data.get("issues"),
            "complexity": data.get("complexity"),
            "fixed_code": data.get("fixed")
        }

        return json.dumps(clean_data, indent=2)

    def severity_report(self, issues):
        """Advanced severity classification"""

        report = {
            "CRITICAL": [],
            "MEDIUM": [],
            "LOW": []
        }

        for issue in issues:

            score = issue.get("score", 0)

            if score >= 0.85:
                report["CRITICAL"].append(issue)

            elif score >= 0.6:
                report["MEDIUM"].append(issue)

            else:
                report["LOW"].append(issue)

        return report